name: examen_practico_g61_starter
description: Starter para el Examen Practico 1 - Grupo 61.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  loading_animation_widget:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
